config/routes.rb
Rails.application.routes.draw do
  
  
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'search' => "searches#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
    
  validates :body, presence: true,
    length: { maximum: 200 }
  
  def self.looks(search,word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :profile_image
  
  validates :name,
    length: { minimum: 2, maximum: 20 },
    uniqueness: true
    
  validates :introduction, length: { maximum: 50 }

  def self.looks(search,word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!,except: [:top, :about]
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end
  
  def edit
    @user = User.find(params[:id])
    
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user.id)
    else 
      render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<h2>New book</h2>
<%= form_with model:book, local:true do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Opinion</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book', class: 'btn btn-success' %>

<% end %>

app/views/books/edit.html.erb
<main class="mb-auto">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
  
        <% if @book.errors.any? %>
          error
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        
        <%= form_with model:@book, local:true do |f| %>
        
          <div>
            <label>Title</label> </br>
            <%= f.text_field :title %>
          </div>
        
          <div>
            <label>Opinion</label></br> 
            <%= f.text_area :body %>
          </div>
        
          <div>
            <%= f.submit "Update Book" %>
          </div>
        <% end %>
        
        <%= link_to "Show", book_path(@book.id) %>
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/index.html.erb
<main class="mb-auto">
  <% if @book.errors.any? %>
    error
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/user', user: @user %>
        <%= render 'books/book', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg"%>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
                <td>
                  <% if book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <i class="fas fa-heart"></i>
                      <%= book.favorites.count %>
                    <% end %>
                  <% else %>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <i class="far fa-heart"></i>
                      <%= book.favorites.count %>
                    <% end %>
                  <% end %>
                </td>
                <td>
                  コメント数: <%= "#{book.book_comments.count}" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>  

app/views/books/show.html.erb
<main class="mb-auto">
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
  
  <% if @book.errors.any? %>
    error
  <% end %>
  
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <%= render 'books/book', book: @newbook %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h1>Book details</h1>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg"%> </br>
                  <%= @user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td><%= @book.body %></td>
              <td>
                <% if @book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(@book), method: :delete do %>
                      <i class="fas fa-heart"></i>
                      <%= @book.favorites.count %>
                    <% end %>
                  <% else %>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      <i class="far fa-heart"></i>
                      <%= @book.favorites.count %>
                    <% end %>
                  <% end %>
              </td>
              <td>コメント数: <%= @book.book_comments.count %></td>
              <% if @book.user_id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
        
        <% @book.book_comments.each do |comment| %>
         <div>
           <%= attachment_image_tag comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg"%> 
           <%= comment.comment %>
           <% if comment.user == current_user %>
             <%= link_to "Destroy", book_book_comment_path(comment.book, comment), method: :delete, class:"btn btn-danger" %>
           <% end %> 
           </br>
           <%= link_to user_path(@user) do %>
             <%= comment.user.name %>
           <% end %>
          </div>
        <% end %>
         
        
        <%= form_with(model:[@book, @book_comment], local:true) do |f| %>
          <%= f.text_area :comment %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>